#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TSbb_Android.Resource", IsApplication=true)]

namespace TSbb_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int BetonSpinner_Elements = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int StahlSpinner_Elements = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int BetonLabel = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int BetonSpinner = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int MEd = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int PhiBew = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int StahlLabel = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int StahlSpinner = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int bTräger = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int cnom = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int hTräger = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int tableLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int tableRow1 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int tableRow2 = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow3 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int tableRow4 = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int tableRow5 = 2131034134;
			
			// aapt resource value: 0x7f050007
			public const int textView10 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textView11 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int textView12 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView13 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int textView14 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int textView15 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int textView16 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int textView17 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int textView18 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int textView19 = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int BetonSpinner_Prompt = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int StahlSpinner_Prompt = 2130903042;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
